#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPageService
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="WebPage")]
	public partial class DataContextDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertItemImage(ItemImage instance);
    partial void UpdateItemImage(ItemImage instance);
    partial void DeleteItemImage(ItemImage instance);
    partial void InsertItem(Item instance);
    partial void UpdateItem(Item instance);
    partial void DeleteItem(Item instance);
    #endregion
		
		public DataContextDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["WebPageConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataContextDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataContextDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataContextDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataContextDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ItemImage> ItemImages
		{
			get
			{
				return this.GetTable<ItemImage>();
			}
		}
		
		public System.Data.Linq.Table<Item> Items
		{
			get
			{
				return this.GetTable<Item>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ItemImages")]
	public partial class ItemImage : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _ItemId;
		
		private string _Url;
		
		private EntityRef<Item> _Item;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnItemIdChanging(int value);
    partial void OnItemIdChanged();
    partial void OnUrlChanging(string value);
    partial void OnUrlChanged();
    #endregion
		
		public ItemImage()
		{
			this._Item = default(EntityRef<Item>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemId", DbType="Int NOT NULL")]
		public int ItemId
		{
			get
			{
				return this._ItemId;
			}
			set
			{
				if ((this._ItemId != value))
				{
					if (this._Item.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnItemIdChanging(value);
					this.SendPropertyChanging();
					this._ItemId = value;
					this.SendPropertyChanged("ItemId");
					this.OnItemIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Url", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Url
		{
			get
			{
				return this._Url;
			}
			set
			{
				if ((this._Url != value))
				{
					this.OnUrlChanging(value);
					this.SendPropertyChanging();
					this._Url = value;
					this.SendPropertyChanged("Url");
					this.OnUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Item_ItemImage", Storage="_Item", ThisKey="ItemId", OtherKey="Id", IsForeignKey=true)]
		public Item Item
		{
			get
			{
				return this._Item.Entity;
			}
			set
			{
				Item previousValue = this._Item.Entity;
				if (((previousValue != value) 
							|| (this._Item.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Item.Entity = null;
						previousValue.ItemImages.Remove(this);
					}
					this._Item.Entity = value;
					if ((value != null))
					{
						value.ItemImages.Add(this);
						this._ItemId = value.Id;
					}
					else
					{
						this._ItemId = default(int);
					}
					this.SendPropertyChanged("Item");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Items")]
	public partial class Item : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Name_Geo;
		
		private string _Name_Rus;
		
		private string _Name_Eng;
		
		private string _Description_Geo;
		
		private string _Description_Rus;
		
		private string _Description_Eng;
		
		private string _VideoLink_Geo;
		
		private string _VideoLink_Rus;
		
		private string _VideoLink_Eng;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private EntitySet<ItemImage> _ItemImages;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnName_GeoChanging(string value);
    partial void OnName_GeoChanged();
    partial void OnName_RusChanging(string value);
    partial void OnName_RusChanged();
    partial void OnName_EngChanging(string value);
    partial void OnName_EngChanged();
    partial void OnDescription_GeoChanging(string value);
    partial void OnDescription_GeoChanged();
    partial void OnDescription_RusChanging(string value);
    partial void OnDescription_RusChanged();
    partial void OnDescription_EngChanging(string value);
    partial void OnDescription_EngChanged();
    partial void OnVideoLink_GeoChanging(string value);
    partial void OnVideoLink_GeoChanged();
    partial void OnVideoLink_RusChanging(string value);
    partial void OnVideoLink_RusChanged();
    partial void OnVideoLink_EngChanging(string value);
    partial void OnVideoLink_EngChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    #endregion
		
		public Item()
		{
			this._ItemImages = new EntitySet<ItemImage>(new Action<ItemImage>(this.attach_ItemImages), new Action<ItemImage>(this.detach_ItemImages));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name_Geo", DbType="NVarChar(MAX)")]
		public string Name_Geo
		{
			get
			{
				return this._Name_Geo;
			}
			set
			{
				if ((this._Name_Geo != value))
				{
					this.OnName_GeoChanging(value);
					this.SendPropertyChanging();
					this._Name_Geo = value;
					this.SendPropertyChanged("Name_Geo");
					this.OnName_GeoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name_Rus", DbType="NVarChar(MAX)")]
		public string Name_Rus
		{
			get
			{
				return this._Name_Rus;
			}
			set
			{
				if ((this._Name_Rus != value))
				{
					this.OnName_RusChanging(value);
					this.SendPropertyChanging();
					this._Name_Rus = value;
					this.SendPropertyChanged("Name_Rus");
					this.OnName_RusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name_Eng", DbType="NVarChar(MAX)")]
		public string Name_Eng
		{
			get
			{
				return this._Name_Eng;
			}
			set
			{
				if ((this._Name_Eng != value))
				{
					this.OnName_EngChanging(value);
					this.SendPropertyChanging();
					this._Name_Eng = value;
					this.SendPropertyChanged("Name_Eng");
					this.OnName_EngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description_Geo", DbType="NVarChar(MAX)")]
		public string Description_Geo
		{
			get
			{
				return this._Description_Geo;
			}
			set
			{
				if ((this._Description_Geo != value))
				{
					this.OnDescription_GeoChanging(value);
					this.SendPropertyChanging();
					this._Description_Geo = value;
					this.SendPropertyChanged("Description_Geo");
					this.OnDescription_GeoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description_Rus", DbType="NVarChar(MAX)")]
		public string Description_Rus
		{
			get
			{
				return this._Description_Rus;
			}
			set
			{
				if ((this._Description_Rus != value))
				{
					this.OnDescription_RusChanging(value);
					this.SendPropertyChanging();
					this._Description_Rus = value;
					this.SendPropertyChanged("Description_Rus");
					this.OnDescription_RusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description_Eng", DbType="NVarChar(MAX)")]
		public string Description_Eng
		{
			get
			{
				return this._Description_Eng;
			}
			set
			{
				if ((this._Description_Eng != value))
				{
					this.OnDescription_EngChanging(value);
					this.SendPropertyChanging();
					this._Description_Eng = value;
					this.SendPropertyChanged("Description_Eng");
					this.OnDescription_EngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VideoLink_Geo", DbType="NVarChar(MAX)")]
		public string VideoLink_Geo
		{
			get
			{
				return this._VideoLink_Geo;
			}
			set
			{
				if ((this._VideoLink_Geo != value))
				{
					this.OnVideoLink_GeoChanging(value);
					this.SendPropertyChanging();
					this._VideoLink_Geo = value;
					this.SendPropertyChanged("VideoLink_Geo");
					this.OnVideoLink_GeoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VideoLink_Rus", DbType="NVarChar(MAX)")]
		public string VideoLink_Rus
		{
			get
			{
				return this._VideoLink_Rus;
			}
			set
			{
				if ((this._VideoLink_Rus != value))
				{
					this.OnVideoLink_RusChanging(value);
					this.SendPropertyChanging();
					this._VideoLink_Rus = value;
					this.SendPropertyChanged("VideoLink_Rus");
					this.OnVideoLink_RusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VideoLink_Eng", DbType="NVarChar(MAX)")]
		public string VideoLink_Eng
		{
			get
			{
				return this._VideoLink_Eng;
			}
			set
			{
				if ((this._VideoLink_Eng != value))
				{
					this.OnVideoLink_EngChanging(value);
					this.SendPropertyChanging();
					this._VideoLink_Eng = value;
					this.SendPropertyChanged("VideoLink_Eng");
					this.OnVideoLink_EngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Item_ItemImage", Storage="_ItemImages", ThisKey="Id", OtherKey="ItemId")]
		public EntitySet<ItemImage> ItemImages
		{
			get
			{
				return this._ItemImages;
			}
			set
			{
				this._ItemImages.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ItemImages(ItemImage entity)
		{
			this.SendPropertyChanging();
			entity.Item = this;
		}
		
		private void detach_ItemImages(ItemImage entity)
		{
			this.SendPropertyChanging();
			entity.Item = null;
		}
	}
}
#pragma warning restore 1591
